version: '3.8'
services:
  uni-qr-db:
    image: postgres:14.7-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root_root
    ports:
      - "15433:5433"
    volumes:
      - ./infrastructure/db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - db-data:/server/var/lib/postgresql/data
    restart: unless-stopped

  uni-qr-server:
    image: uni-qr-server:0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - uni-qr-db
    environment:
      - SERVER_PORT=8081
      - SPRING_DATASOURCE_URL=jdbc:postgresql://uni-qr-db/uniqr

  pgadmin:
    image: dpage/pgadmin4:7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: dmitriy.s.stepanenko@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 2OXAOIlhqv1UjJt
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  db-data:
  pgadmin-data: